machine:
  hosts:
    circlehost: 127.0.0.1

  dependencies:
    pre:
      - sudo apt-get update
      - sudo apt-get install iverilog
      
  database:
    override:
       # replace CircleCI's generated database.yml
      - cp config/database.yml.ci config/database.yml
      - bundle exec rake db:create db:schema:load
    
 
