version: 1.0
  
dependencies:
  pre:
    - sudo apt-get update
    - sudo apt-get iverilog
    
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          working_directory: ~/pux_si
          command: ./compile.sh pux_si_tb
      - run:
          working_directory: ~/pux_si
          command: ./simulate.sh
    
 
