version: 1.0
  
dependencies:
  pre:
    - sudo apt-get update
    - sudo apt-get iverilog
    
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install IVERILOG
          command: sudo apt-get update && sudo apt-get install iverilog   
      - run:
          name: Compile the project
          working_directory: ./pux_si
          command: ./compile.sh pux_si_tb
      - run:
          name: Run sample test
          working_directory: ./pux_si
          command: ./simulate.sh
    
 
