version: 1.0
  
dependencies:
  pre:
    - sudo apt-get update
    - sudo apt-get iverilog
    
jobs:
  working_directory: ~/pux_si
  build:
    steps:
      - checkout
      - ./compile.sh pux_si_tb
      - ./simulate.sh
    
 
